import { StyleSheet, Platform, StatusBar } from 'react-native';
import { scale, verticalScale, moderateScale } from '../utils/scale';

export const COLORS = {
    primary:      '#D63375',
    primaryLight: '#FFB0CE',
    background:   '#FFF0F3',
    bg:           '#FFF0F3',
    white:        '#FFFFFF',
    card:         '#FFFFFF',
    darkText:     '#1C1C1C',
    dark:         '#2D1B2E',
    grayText:     '#9E9E9E',
    muted:        '#B5B7C0',
    lightPink:    '#FDE8F0',
    border:       '#F0D6E2',
};

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.bg,
    },

    // ── top row ───────────────────────────────────────────────────────────────
    topRow: {
        flexDirection:    'row',
        justifyContent:   'space-between',
        alignItems:       'center',
        paddingHorizontal: scale(16),
        paddingTop: Platform.OS === 'ios'
            ? verticalScale(54)
            : StatusBar.currentHeight + verticalScale(8),
        paddingBottom: verticalScale(8),
    },
    backBtn: {
        width: scale(36),
        height: scale(36),
        borderRadius: scale(18),
        backgroundColor: COLORS.white,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    topRowRight: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    iconBtn:     { position: 'relative' },
    avatar:      { width: 36, height: 36, borderRadius: 18 },

    // ── header ────────────────────────────────────────────────────────────────
    headerSection: {
        paddingHorizontal: scale(20),
        paddingTop:        verticalScale(4),
        paddingBottom:     verticalScale(10),
    },
    headerTitleRow: {
        flexDirection: 'row',
        alignItems:    'center',
        gap:           10,
        marginBottom:  4,
    },
    headerIconBadge: {
        width:           34,
        height:          34,
        borderRadius:    10,
        alignItems:      'center',
        justifyContent:  'center',
        backgroundColor: COLORS.primary,
    },
    headerTitle: {
        fontSize:   moderateScale(24),
        fontWeight: '700',
        color:      COLORS.dark,
    },
    headerSub: {
        fontSize:   moderateScale(13),
        fontWeight: '600',
        color:      COLORS.primary,
    },

    // ── scroll ────────────────────────────────────────────────────────────────
    scrollContent: {
        paddingBottom:     verticalScale(100),
        paddingHorizontal: 16,
    },

    // ── loading / empty ───────────────────────────────────────────────────────
    loadingContainer: {
        flex:           1,
        justifyContent: 'center',
        alignItems:     'center',
    },
    emptyContainer: {
        alignItems:        'center',
        marginTop:          60,
        gap:                12,
        paddingHorizontal: 32,
    },
    emptyIconWrap: {
        width:           68,
        height:          68,
        borderRadius:    34,
        backgroundColor: COLORS.lightPink,
        alignItems:      'center',
        justifyContent:  'center',
        marginBottom:    4,
    },
    emptyText: {
        fontSize:   15,
        fontWeight: '700',
        color:      COLORS.dark,
    },
    emptySubText: {
        fontSize:   13,
        color:      COLORS.muted,
        textAlign:  'center',
        lineHeight: 19,
    },

    // ── stats row ─────────────────────────────────────────────────────────────
    statsRow: {
        flexDirection: 'row',
        gap:           10,
        marginBottom:  16,
    },
    statCard: {
        flex:              1,
        backgroundColor:   COLORS.card,
        borderRadius:      14,
        paddingVertical:   12,
        paddingHorizontal: 12,
        borderWidth:       1,
        borderColor:       COLORS.border,
        alignItems:        'flex-start',
    },
    statCardActive:   { borderTopWidth: 3, borderTopColor: '#DC2626' },
    statCardResolved: { borderTopWidth: 3, borderTopColor: '#16A34A' },
    statCardClosed:   { borderTopWidth: 3, borderTopColor: '#9CA3AF' },
    statIconWrap: {
        width:           28,
        height:          28,
        borderRadius:    8,
        backgroundColor: '#FEE2E2',
        alignItems:      'center',
        justifyContent:  'center',
        marginBottom:    8,
    },
    statIconResolved: { backgroundColor: '#DCFCE7' },
    statIconClosed:   { backgroundColor: '#F3F4F6' },
    statLabel: {
        fontSize:      10,
        color:         COLORS.muted,
        fontWeight:    '600',
        marginBottom:  2,
        textTransform: 'uppercase',
        letterSpacing: 0.4,
    },
    statValue: {
        fontSize:   22,
        fontWeight: '700',
        color:      COLORS.dark,
        lineHeight: 26,
    },
    statSub: {
        fontSize:  10,
        color:     COLORS.muted,
        fontWeight:'400',
        marginTop: 2,
    },

    // ── filter row ────────────────────────────────────────────────────────────
    filterRow: {
        flexDirection: 'row',
        gap:           10,
        marginBottom:  14,
        alignItems:    'center',
        zIndex:        20,
    },
    dropdownWrapper: {
        position:   'relative',
        flexShrink: 0,
    },
    filterBtn: {
        flexDirection:     'row',
        alignItems:        'center',
        gap:               6,
        backgroundColor:   COLORS.primary,
        borderRadius:      20,
        paddingVertical:   8,
        paddingHorizontal: 14,
    },
    filterBtnText: {
        fontSize:   13,
        color:      COLORS.white,
        fontWeight: '600',
    },
    urgencyBtn: {
        flexDirection:     'row',
        alignItems:        'center',
        gap:               6,
        backgroundColor:   COLORS.white,
        borderRadius:      20,
        paddingVertical:   8,
        paddingHorizontal: 14,
        borderWidth:       1.5,
        borderColor:       COLORS.primary,
    },
    urgencyBtnText: {
        fontSize:   13,
        color:      COLORS.primary,
        fontWeight: '600',
    },
    resultCount: {
        marginLeft: 'auto',
        fontSize:   12,
        color:      COLORS.muted,
        fontWeight: '500',
    },
    filterDropdown: {
        position:        'absolute',
        top:             38,
        left:            0,
        backgroundColor: COLORS.white,
        borderRadius:    12,
        paddingVertical: 6,
        width:           140,
        borderWidth:     1,
        borderColor:     COLORS.border,
        shadowColor:     '#000',
        shadowOffset:    { width: 0, height: 2 },
        shadowOpacity:   0.1,
        shadowRadius:    6,
        elevation:       4,
        zIndex:          100,
    },
    dropdownItem: {
        paddingVertical:   10,
        paddingHorizontal: 16,
    },
    dropdownItemText: {
        fontSize: 13,
        color:    COLORS.dark,
    },
    dropdownItemTextActive: {
        color:      COLORS.primary,
        fontWeight: '600',
    },

    activeFiltersScroll: {
        flex: 1,
    },
    activeFiltersContainer: {
        flexDirection: 'row',
        gap:           6,
        alignItems:    'center',
    },
    activeFilterBadge: {
        flexDirection:     'row',
        alignItems:        'center',
        gap:               4,
        backgroundColor:   COLORS.white,
        borderRadius:      20,
        paddingVertical:   6,
        paddingHorizontal: 12,
        borderWidth:       1,
        borderColor:       COLORS.border,
    },
    activeFilterBadgeText: {
        fontSize: 12,
        color:    COLORS.dark,
    },

    // ── request card ──────────────────────────────────────────────────────────
    requestCard: {
        backgroundColor:   COLORS.card,
        borderRadius:      16,
        marginBottom:      12,
        borderLeftWidth:   4,
        borderLeftColor:   COLORS.primary,
        borderWidth:       1,
        borderColor:       COLORS.border,
        shadowColor:       '#000',
        shadowOffset:      { width: 0, height: 2 },
        shadowOpacity:     0.04,
        shadowRadius:      6,
        elevation:         2,
    },
    cardHeader: {
        padding: 14,
    },
    chipIdRow: {
        flexDirection:     'row',
        justifyContent:    'space-between',
        alignItems:        'center',
        marginBottom:      8,
    },
    categoryChip: {
        flexDirection:     'row',
        alignItems:        'center',
        gap:               4,
        backgroundColor:   COLORS.lightPink,
        borderRadius:      20,
        paddingHorizontal: 8,
        paddingVertical:   3,
        borderWidth:       1,
        borderColor:       COLORS.border,
    },
    categoryChipText: {
        fontSize:   10,
        color:      COLORS.primary,
        fontWeight: '600',
    },
    reqIdPill: {
        flexDirection: 'row',
        alignItems:    'center',
        gap:           2,
        backgroundColor: '#F3F4F6',
        borderRadius:    6,
        paddingHorizontal: 6,
        paddingVertical: 2,
    },
    reqIdPillText: {
        fontSize:   10,
        color:      '#4B5563',
        fontWeight: '700',
    },
    cardTitleRow: {
        flexDirection: 'row',
        alignItems:    'center',
        justifyContent: 'space-between',
        gap:           12,
        marginBottom:  10,
    },
    cardTitle: {
        flex:       1,
        fontSize:   16,
        fontWeight: '700',
        color:      COLORS.dark,
        lineHeight: 22,
    },
    collapseBtn: {
        padding:         4,
        borderRadius:    20,
        backgroundColor: COLORS.lightPink,
    },
    badgeRow: {
        flexDirection: 'row',
        gap:           8,
        alignItems:    'center',
        marginTop:     2,
    },
    badge: {
        paddingHorizontal: 8,
        paddingVertical:   4,
        borderRadius:      20,
        borderWidth:       0.5,
        borderColor:       'rgba(0,0,0,0.05)',
    },
    badgeInner: {
        flexDirection: 'row',
        alignItems:    'center',
        gap:           4,
    },
    badgeDot: {
        width:         6,
        height:        6,
        borderRadius:  3,
    },
    badgeText: {
        fontSize:   9,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 0.3,
    },
    criticalBadge: {
        backgroundColor: '#DC2626',
        borderRadius:    6,
        paddingHorizontal: 6,
        paddingVertical: 2,
    },
    criticalText: {
        fontSize: 9,
        fontWeight: '800',
        color: COLORS.white,
        letterSpacing: 0.5,
    },
    pulseDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#DC2626',
    },
    cardDivider: {
        height:          1,
        backgroundColor: COLORS.border,
        marginHorizontal: 14,
    },

    // ── card body ─────────────────────────────────────────────────────────────
    cardBody: {
        padding: 14,
        gap:     10,
    },
    bodyDetailCard: {
        backgroundColor: '#FFF8FA',
        borderRadius:    12,
        padding:         12,
        borderWidth:     1,
        borderColor:     'rgba(240, 214, 226, 0.4)',
    },
    bodyDetailHeader: {
        flexDirection: 'row',
        alignItems:    'center',
        gap:           6,
        marginBottom:  4,
    },
    bodyDetailLabel: {
        fontSize:     11,
        color:        COLORS.primary,
        fontWeight:   '700',
        textTransform: 'uppercase',
        letterSpacing: 0.3,
    },
    bodyDetailValue: {
        fontSize:   13,
        color:      COLORS.dark,
        lineHeight: 18,
        fontWeight: '500',
    },
    adminResponseCard: {
        backgroundColor: '#FFF0F5',
        borderRadius:    12,
        padding:         12,
        borderWidth:     1,
        borderColor:     COLORS.border,
        marginTop:       4,
    },
    adminResponseHeader: {
        flexDirection: 'row',
        alignItems:    'center',
        gap:           6,
        marginBottom:  6,
    },
    adminResponseTitle: {
        fontSize:     11,
        color:        COLORS.dark,
        fontWeight:   '800',
        textTransform: 'uppercase',
        letterSpacing: 0.4,
    },
    adminResponseText: {
        fontSize:   12,
        color:      '#374151',
        lineHeight: 18,
        fontWeight: '500',
    },
    cardFooter: {
        padding: 14,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    footerDateRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    footerDate: {
        fontSize: 12,
        color: '#4B5563',
        fontWeight: '600',
    },
    footerToggleText: {
        fontSize: 11,
        color: COLORS.primary,
        fontWeight: '700',
    },

    bottomNav: {
        flexDirection: 'row',
        backgroundColor: COLORS.white,
        paddingBottom: Platform.OS === 'ios' ? verticalScale(20) : verticalScale(10),
        paddingTop: verticalScale(10),
        paddingHorizontal: scale(10),
        borderTopWidth: 1,
        borderTopColor: '#F0F0F0',
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
    },
    navItem: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    navLabel: {
        fontSize: 10,
        color: COLORS.muted,
        marginTop: 2,
    },
    navCenter: {
        marginTop: -22,
    },
    navCenterCircle: {
        width: scale(56),
        height: scale(56),
        borderRadius: scale(28),
        backgroundColor: COLORS.primary,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 6,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
    },

    // ── swipeable list item styles ─────────────────────────────────────────────
    swipeContainer: {
        position: 'relative',
        overflow: 'hidden',
    },
    swipeActionContainer: {
        position: 'absolute',
        right: 0,
        top: 0,
        bottom: 12,
        width: 80,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FDE8F0',
        borderWidth: 1,
        borderColor: '#F0D6E2',
        borderTopRightRadius: 16,
        borderBottomRightRadius: 16,
        overflow: 'hidden',
    },
    swipeActionButton: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
});
